<?php

namespace Database\Seeders;

use App\Models\Ticket;
use App\Models\TicketAnswer;
use App\Models\TicketForm;
use App\Models\User;
use Illuminate\Database\Seeder;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        if (!$user) {
            $this->command->warn('No users found. Seed users first.');
            return;
        }

        $forms = TicketForm::with('fields')->get();

        foreach ($forms as $form) {

            $ticket = Ticket::create([
                'user_id' => $user->id,
                'ticket_form_id' => $form->id,
                'title' => $form->name . ' Sample Ticket',
                'description' => 'This is a sample ticket generated by the seeder.',
                'priority' => collect(['low', 'medium', 'high'])->random(),
                'status' => 'open',
                'assign_to' => null,
            ]);

            $answers = [];

            foreach ($form->fields as $field) {

                $value = match ($field->type) {

                    'text' => 'Sample Text',

                    'textarea' => 'This is a sample textarea value.',

                    'number' => 10,

                    'date' => now()->toDateString(),

                    'email' => 'demo@example.com',

                    'select' => is_array($field->options)
                        ? ($field->options[0] ?? null)
                        : (
                            json_decode($field->options, true)[0] ?? null
                        ),

                    default => 'Sample Value',
                };

                $answers[] = [
                    'field_id' => $field->id,
                    'field_name' => $field->name,
                    'field_label' => $field->label,
                    'field_type' => $field->type,
                    'value' => $value,
                ];
            }

            TicketAnswer::create([
                'ticket_id' => $ticket->id,
                'answers' => $answers,
            ]);
        }
    }
}
